server:
  port: 8082
  servlet:
    context-path: /
    tomcat:
      uri-encoding: UTF-8
      max-threads: 200
spring:
    application:
        name: configclient1
    # rabbitMQ连接配置
    rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: admin
      password: admin

mynametest: 1233332a
